# Generated by Django 4.1.1 on 2022-09-06 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geral', '0001_initial'),
        ('movimentacoes', '0002_movimentacao_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geral.categoria', verbose_name='Categoria'),
        ),
    ]
